{
  config,
  pkgs,
  lib,
  ...
}: let
  inherit (lib) getAttrFromPath mkIf mkOption setAttrByPath types;

  modulePath = [
    "programs"
    "zen-browser"
  ];

  cfg = getAttrFromPath modulePath config;

  linuxConfigPath = "${config.xdg.configHome}/zen";
  darwinConfigPath = "${config.home.homeDirectory}/Library/Application Support/Zen";

  profilePath = "${(
    if pkgs.stdenv.isDarwin
    then "${darwinConfigPath}/Profiles"
    else linuxConfigPath
  )}";
in {
  options = setAttrByPath modulePath {
    profiles = mkOption {
      type = with types;
        attrsOf (
          submodule (
            {...}: {
              options = {
                mods = mkOption {
                  type = listOf str;
                  default = [];
                  description = "List of mod UUIDs to install from the Zen theme store.";
                };
              };
            }
          )
        );
    };
  };

  config = mkIf cfg.enable {
    home.activation = let
      inherit
        (lib)
        filterAttrs
        mapAttrs'
        nameValuePair
        ;

      profilesWithMods =
        filterAttrs
        (_: profile: profile.mods != [])
        cfg.profiles;
    in
      mapAttrs'
      (
        profileName: profile: let
          themesFilePath = "${profilePath}/${profileName}/zen-themes.json";

          updateModsScript = pkgs.writeShellScript "zen-mods-update-${profileName}" /* bash */ ''
                      THEMES_FILE="${themesFilePath}"
                      MODS="${lib.concatStringsSep " " profile.mods}"
                      BASE_DIR="${profilePath}/${profileName}"
                      MANAGED_FILE="$BASE_DIR/zen-mods-nix-managed.json"

                      if [ ! -f "$THEMES_FILE" ]; then
                        echo '{}' > "$THEMES_FILE"
                      fi

                      # Read current managed mods
                      if [ -f "$MANAGED_FILE" ]; then
                        CURRENT_MANAGED=$(${lib.getExe pkgs.jq} -r '.[]' "$MANAGED_FILE" 2>/dev/null || echo "")
                      else
                        CURRENT_MANAGED=""
                      fi

                      # Remove mods not in current list
                      for uuid in $CURRENT_MANAGED; do
                        if [[ " $MODS " != *" $uuid "* ]]; then
                          ${lib.getExe pkgs.jq} "del(.[\"$uuid\"])" "$THEMES_FILE" > "$THEMES_FILE.tmp" && mv "$THEMES_FILE.tmp" "$THEMES_FILE"
                          rm -rf "$BASE_DIR/chrome/zen-themes/$uuid"
                          echo "Removed mod $uuid"
                        fi
                      done

                      # Install/update current mods
                      for mod_uuid in $MODS; do
                        MOD_DIR="$BASE_DIR/chrome/zen-themes/$mod_uuid"
                        if [ -d "$MOD_DIR" ]; then
                          continue
                        fi

                        THEME_URL="https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/$mod_uuid/theme.json"
                        echo "Fetching mod $mod_uuid from $THEME_URL"

                        THEME_JSON=$(${lib.getExe pkgs.curl} -s "$THEME_URL")
                        if [ $? -ne 0 ] || [ -z "$THEME_JSON" ]; then
                          echo "Failed to fetch theme for mod $mod_uuid"
                          continue
                        fi

                        if ! echo "$THEME_JSON" | ${lib.getExe pkgs.jq} empty 2>/dev/null; then
                          echo "Invalid JSON for mod $mod_uuid"
                          continue
                        fi

                        # Merge into themes file
                        ${lib.getExe pkgs.jq} --arg uuid "$mod_uuid" --argjson theme "$THEME_JSON" '.[$uuid] = $theme' "$THEMES_FILE" > "$THEMES_FILE.tmp" && mv "$THEMES_FILE.tmp" "$THEMES_FILE"

                        # Download mod files
                        mkdir -p "$MOD_DIR"

                        for file in chrome.css preferences.json readme.md; do
                          FILE_URL="https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/$mod_uuid/$file"
                          ${lib.getExe pkgs.curl} -s "$FILE_URL" -o "$MOD_DIR/$file" || true
                        done
                      done

                      # Write new managed list
                      echo "$MODS" | tr ' ' '\n' | ${lib.getExe pkgs.jq} -R -s 'split("\n") | map(select(. != ""))' > "$MANAGED_FILE"

                      # Generate zen-themes.css
                      ZEN_THEMES_CSS="$BASE_DIR/chrome/zen-themes.css"
                      echo "/* Zen Mods - Generated by Zen Browser Flake." > "$ZEN_THEMES_CSS"
                      cat >> "$ZEN_THEMES_CSS" << 'EOF'
            * DO NOT EDIT THIS FILE DIRECTLY!
            * Your changes will be overwritten.
            * Instead, go to the preferences and edit the mods there.
            */
            EOF

                      # Get enabled mods
                      ENABLED_MODS=$(${lib.getExe pkgs.jq} -r 'to_entries[] | select(.value.enabled == null or .value.enabled == true) | .key' "$THEMES_FILE")

                      for mod_uuid in $ENABLED_MODS; do
                        MOD_CSS="$BASE_DIR/chrome/zen-themes/$mod_uuid/chrome.css"
                        if [ -f "$MOD_CSS" ]; then
                          MOD_INFO=$(${lib.getExe pkgs.jq} -r ".\"$mod_uuid\" | \"/* Name: \(.name) */\\n/* Description: \(.description) */\\n/* Author: @\(.author) */\"" "$THEMES_FILE")
                          echo "$MOD_INFO" >> "$ZEN_THEMES_CSS"
                          cat "$MOD_CSS" >> "$ZEN_THEMES_CSS"
                          echo "" >> "$ZEN_THEMES_CSS"
                        fi
                      done

                      echo "/* End of Zen Mods */" >> "$ZEN_THEMES_CSS"

                      if ! ${lib.getExe pkgs.jq} empty "$THEMES_FILE" 2>/dev/null; then
                        echo "Error: Generated invalid JSON in $THEMES_FILE"
                        exit 1
                      fi
          '';
        in
          nameValuePair "zen-mods-${profileName}" (lib.hm.dag.entryAfter ["writeBoundary"] ''
            ${updateModsScript}
            if [[ "$?" -eq 0 ]]; then
              $VERBOSE_ECHO "zen-mods: Updated mods for profile '${profileName}'"
            else
              echo "zen-mods: Failed to update mods for profile '${profileName}'!" >&2
            fi
          '')
      )
      profilesWithMods;
  };
}
