runOnDraft: false
addReviewers: true
addAssignees: author
reviewers:
  - luisnquin

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 0
