name: Deploy docs

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-docs
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Setup Nix cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Generate docs options
        run: nix run .#docs-options

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: "4.103.0"
          command: deploy
