name: Pull request setup
on:
  pull_request:
    types:
      - opened
      - ready_for_review

permissions:
  contents: read
  pull-requests: write

jobs:
  add-reviewers-assignees:
    name: Add reviewers and assignees
    runs-on: ubuntu-latest
    steps:
      - name: Add reviewers and assignees
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: .github/auto_assign.yml
