name: Check *.nix files format
on: [push, pull_request]

jobs:
  check-formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Alejandra CLI
        uses: luisnquin/setup-alejandra@v1.0.0

      - name: Check formatting
        run: alejandra --check **/*.nix
